import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/utils/ThemeProvider";
import { NextAuthProvider } from "./provider";
import Header from "@/components/Header";
import { Suspense } from "react";
import Loading from './loading';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DevMeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Suspense fallback={<Loading />}>
              <Header />
              {children}
            </Suspense>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
